name: Auto refresh documentation

on: workflow_dispatch

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Download new files from NIIS
        run: |
          cd automatics
          chmod +x refresh.sh
          ./refresh.sh ${GITHUB_REF##*/} $(cat version.txt)
      - name: Clean old files
        run: |
          cd automatics
          chmod +x clean.sh
          ./clean.sh ${GITHUB_REF##*/} $(cat version.txt)
      - name: Push changes to the repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "$(date +'%Y-%m-%dT%H:%M:%S')" >> audit.txt
          git add .
          git commit -m "${GITHUB_REF##*/}"
          git push



      
