name: refresh documentation

on: workflow_dispatch

env:
  PREV_VERSION: 7.2.2
  VERSION_TO_REFRESH: ${GITHUB_REF##*/}

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x refresh.sh
          rm -rf v_$VERSION_TO_REFRESH
          ./refresh.sh $PREV_VERSION $VERSION_TO_REFRESH
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x test.sh 
          ./test.sh $VERSION_TO_REFRESH
          git add .
          git commit -m "test_$VERSION_TO_REFRESH"
          git push
