name: 1. refresh documentation

on: workflow_dispatch

env:
  PREV_VERSION: 7.2.2

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x refresh.sh
          rm -rf v_${GITHUB_REF##*/}
          ./refresh.sh ${GITHUB_REF##*/} ${PREV_VERSION}
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x test.sh 
          ./test.sh ${GITHUB_REF##*/}
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push
