name: Auto refresh documentation

on: workflow_dispatch

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf automatics/md_prev
          mv md automatics/md_prev
          cd automatics
          mv version.txt prev_version.txt
          echo ${GITHUB_REF##*/} > version.txt
          ./refresh.sh ${GITHUB_REF##*/} $(echo $(cat prev_version.txt))

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push


      
