name: refresh documentation

on: [push]

env:
  VERSION_TO_REFRESH: 7.3.2

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x refresh.sh
          ./refresh.sh $VERSION_TO_REFRESH
          cp -r md/img v_$VERSION_TO_REFRESH/md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      
      
      
