name: refresh documentation

on: workflow_dispatch

env:
  PREV_VERSION: 7.2.2
  VERSION_TO_REFRESH: 7.2.2

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: $VERSION_TO_REFRESH
      - run: |
          chmod +x refresh.sh
          ./refresh.sh $PREV_VERSION $VERSION_TO_REFRESH
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$VERSION_TO_REFRESH"
          git push
    

      
      
      
