name: Generate html pages

on: workflow_dispatch

jobs:
  convert-files:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Convert md files to html pages
        run: |
          cd automatics
          chmod +x md2html.py
          ./md2html.py
          
      - name: Push changes to the repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "$(date +'%Y-%m-%dT%H:%M:%S')" >> audit.txt
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push



      
