name: Generate html pages

on: workflow_dispatch

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Download new files from NIIS
        run: |
          cd automatics
          chmod +x md2html.py
          ./md2html.py $(cat version.txt)
          
      - name: Push changes to the repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push



      
