name: refresh documentation

on: workflow_dispatch

env:
  PREV_VERSION: 7.3.2

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mv md md_prev
          mv v_${GITHUB_REF##*/} md
          cp md_prev/ig-ss_x-road_v6_security_server_installation_guide.md md
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x test.sh 
          ./test.sh ${GITHUB_REF##*/}
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push
