name: 1. refresh documentation

on: workflow_dispatch

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mv md_prev $(echo md_$(cat old.txt))
          ./clean $(echo md_$(cat old.txt))
          git config user.name github-actions
          git config user.email github-actions@github.com

