name: 3. test documentation

on: workflow_dispatch

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x refresh.sh
          rm -rf v_${GITHUB_REF##*/}
          ./refresh.sh ${GITHUB_REF##*/} ${GITHUB_REF##*/}
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x test.sh 
          ./test.sh ${GITHUB_REF##*/}
          echo "diff_${GITHUB_REF##*/}.md" > clean.sh
          chmod +x clean.sh 
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push
