name: 3. test documentation

on: workflow_dispatch

<<<<<<<< HEAD:.github/workflows/overwrite.yml
env:
  PREV_VERSION: 7.3.2

========
>>>>>>>> 26cd59dd7ae51e2e102833e6120ad08ed3375703:.github/workflows/test.yml
jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
<<<<<<<< HEAD:.github/workflows/overwrite.yml
          mv md md_prev
          mv v_${GITHUB_REF##*/} md
          cp md_prev/ig-ss_x-road_v6_security_server_installation_guide.md md
========
          chmod +x refresh.sh
          rm -rf v_${GITHUB_REF##*/}
          ./refresh.sh ${GITHUB_REF##*/} ${GITHUB_REF##*/}
>>>>>>>> 26cd59dd7ae51e2e102833e6120ad08ed3375703:.github/workflows/test.yml
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x test.sh 
          ./test.sh ${GITHUB_REF##*/}
          git add .
          git commit -m "test_${GITHUB_REF##*/}"
          git push
